"""Default guild configuration keys — must cover all guild_config columns."""
from app.config import settings


def default_guild_config_dict(guild_id: str) -> dict:
    return {
        "guild_id": str(guild_id),
        "channel_buzon_id": None,
        "channel_registro_id": None,
        "channel_historial_id": None,
        "channel_general_id": None,
        "channel_busqueda_id": None,
        "role_buscando_id": None,
        "cooldown_minutes": settings.default_cooldown_minutes,
        "daily_limit": settings.default_daily_limit,
        "auto_mode": 0,
        "timezone": "UTC",
        "language": "es",
        "cmd_registrar_enabled": 1,
        "cmd_registrar_require_channel": 0,
        "cmd_registrar_allowed_channels": "",
        "cmd_renombrar_enabled": 1,
        "cmd_renombrar_require_channel": 0,
        "cmd_renombrar_allowed_channels": "",
        "cmd_perfil_enabled": 1,
        "cmd_perfil_require_channel": 0,
        "cmd_perfil_allowed_channels": "",
        "cmd_stickleaderboard_enabled": 1,
        "cmd_stickleaderboard_require_channel": 0,
        "cmd_stickleaderboard_allowed_channels": "",
        "cmd_partida_enabled": 1,
        "cmd_partida_require_channel": 0,
        "cmd_partida_allowed_channels": "",
        "ansi_enabled": 1,
        "ocr_confidence_threshold": 0.25,
        "ocr_min_points": 30,
        "host_penalty_percent": 8.0,
        "guild_display_name": "",
        "limits_apply_non_admin_only": 0,
        "bot_admin_ids": "",
        "mmr_k_factor": 32.0,
        "partida_confirm_reaction": 0,
        "ocr_margin_percent": 20.0,
        "ocr_center_confidence": 0.25,
        "ocr_corner_confidence": 0.10,
        "ocr_color_distance_max": 170.0,
        "last_ocr_error": None,
        "ansi_preset": "default",
    }
